### ISSUE TITLE
Published posts section should be collapsed upon loading

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#128]
> I find the list of published posts to be annoying since I have to scroll beyond it to see the actual stats. Note that this list doesn’t exist in the Android app, and on the web it’s collapsed.

cc: @nbradbury

**Comment by daniloercoli** [comment]
To be in par with the web version we should remove the Published module.

**Comment by astralbodies** [comment]
Closing as we removed this section.
