### ISSUE TITLE
Track analytics on StatsViewAll and StatsSinglePostDetails

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPressCom-Stats-iOS#147]
See the corresponding Android PR:
https://github.com/wordpress-mobile/WordPress-Android/pull/2213

And be careful to use the same event and property names (https://github.com/wordpress-mobile/WordPress-Android/pull/2213/files).

**Comment by astralbodies** [comment]
StatsSinglePostDetails is a TODO since that feature hasn't been implemented. I'll leave this issue open until then.
