### ISSUE TITLE
Make tappable cells a different color

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#166]
There is no clear indiction if text is clickable or not because they are all the same color.

![links1](https://cloud.githubusercontent.com/assets/373903/6080650/ce8374ea-add8-11e4-8bcb-b19f0f959a36.jpg)

cc: @jancavan

**Comment by jancavan** [comment]
@astralbodies thanks for making the changes, looks good :+1: One more thing - would it be possible to change "View All" to blue as well since it's tappable. Thanks!

**Comment by astralbodies** [comment]
@jancavan I didn't change the color on the View All cell as there is a disclosure indicator accessory view (the chevron on the right) to indicate the row is tappable. Eventually when there is a post details view this should probably get revisited for iOS compatibility rather than the web anchor coloring paradigm we're following.
