### ISSUE TITLE
Parent Lists and Sublists misaligned

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPressCom-Stats-iOS#179]
Current:

![sublist](https://cloud.githubusercontent.com/assets/4924246/6161051/f6bf0208-b21f-11e4-824c-03bab92c1346.png)

Correct:

![sublist-correct](https://cloud.githubusercontent.com/assets/4924246/6161056/07250494-b220-11e4-94ce-cb60ed530f96.png)

**Comment by astralbodies** [comment]
@jancavan If I'm interpreting this properly then I should never indent the nested levels and always line up the child rows with the parent row, correct?

**Comment by jancavan** [comment]
@astralbodies yes, correct about lining up child arrows with parent arrows. In this bug though, the items under the child list (Google Search) needs to be aligned with its parent.

**Comment by astralbodies** [comment]
@jancavan Okay so arrows never indent (which is the case already). If I line up child icons with the parent icon then that effectively removes all indent. In the mock above, following that rule, it would make `Google Search` line up with `Search Engines`.

**Comment by jancavan** [comment]
@astralbodies oh I see what you're saying. Yes, `Google Search` should line up with `Search Engines`. But would it be possible to line up `google.com`, `google.com/search`, etc. line up with `Google Search`?
