### ISSUE TITLE
"View All" item is always on the screen on "Posts & Pages module"

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPressCom-Stats-iOS#213]
![screen shot 2015-02-27 at 14 52 18](https://cloud.githubusercontent.com/assets/518232/6413497/5561bc2a-be90-11e4-97ec-e5dfab34c3f0.png)

**Comment by astralbodies** [comment]
@daniloercoli - I can't reproduce this on my test sites. I did find an instance where I had 10 (not 11) posts and the View All didn't show up. I'm using this value from the remote call which matches the web parser:

https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/blob/develop/WordPressCom-Stats-iOS/WPStatsServiceRemote.m#L587
`BOOL moreViewsAvailable = [firstDay numberForKey:@"other_views"].integerValue > 0;`

Can you see if its still happening?

**Comment by daniloercoli** [comment]
It was probably a temporary error, since i've seen it both on the web and on the iOS app, but then disappeared without patching anything on the server side.

**Comment by astralbodies** [comment]
Cool, thanks for verifying @daniloercoli!
