### ISSUE TITLE
Stats Increased by Previewing Posts

### ISSUE THREAD

**Issue by kevmarsden** [wordpress-mobile/WordPressCom-Stats-iOS#23]
When using the iOS app, a site’s page views stats are increased when a post is previewed. This affects sites when the visibility set to either Public or Private.

This issue was reported by a user in [Helpshift] (https://automattic.helpshift.com/admin/issue/927/) and I was able to replicate it on my test sites. I was not able to replicate this issue using WordPress.com in a web browser.

**Comment by astralbodies** [comment]
Closing as this was ultimately moved to the editor repository: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/99
