### ISSUE TITLE
All-Time Stats View

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPressCom-Stats-iOS#232]
I'm betting that this will progress along with the Calypso stats page, which is looking at hopefully including all-time stats in the future (<a href="https://datap2.wordpress.com/2015/01/19/all-time-stats/">#</a>). But, I wanted to log it here just in case. One of our users requested all-time stats in the mobile app here:

https://twitter.com/Nightbreed1984/status/579094043294052352

I couldn't find a mobile-specific GH issue for it. Is this on the roadmap for future?

**Comment by astralbodies** [comment]
Closed via #262
