### ISSUE TITLE
Styling Changes

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#240]
From: @jancavan

- [x] Add more padding between y-axis and edge of module
- [x] Active x-axis should not be highlighted or have a background color
- [x] Inactive x-axis color should be darken( $gray, 30% ), not $blue-medium
- [x] Remove top border on active tabs
- [x] Expanded lists have 2 top borders, one lighter and the other darker. Please remove the lighter one (topmost)
- [x] Chevron color should be updated to $gray
- [x] Parent lists should have the globe icon
- [x] We can just use a link icon for those URLs that open in a browser window since the right arrow indicates that there are more options in the next screen.
- [x] ~~Can we have these options in the in-app browser – back/forward arrows, page title (with URL at the bottom), refresh and dismiss (x)? Currently, they can only go back, but there’s no way to move forward.~~ => moved to https://github.com/wordpress-mobile/WordPress-iOS/issues/3602
- [x] Some link colors are blue but some are black. All link colors should be $blue-wordpress
- [x] Remove border below segmented control. I think in the past I said this looks ok, sorry about that! On the corrected image, I also added a bit more padding between the module heading and segmented control.
- [x] This kind of preloader feels less obtrusive and users can still switch between tabs.

**Comment by astralbodies** [comment]
@jancavan re:

> We can just use a link icon for those URLs that open in a browser window since the right arrow indicates that there are more options in the next screen.
I'm leaving the right arrow (`UITableViewCellAccessoryDisclosureIndicator`) in place because when stats is embedded in WPiOS, tapping a link does go to the next screen rather than launching Safari. StatsDemo is launching Safari because the web view isn't part of stats but rather built into WPiOS.

**Comment by astralbodies** [comment]
I think we're ready for this to be a design review, @jancavan. I'll push a new version this morning after I look it over as a package. :wink:

**Comment by jancavan** [comment]
Looks good @astralbodies, thanks for making the changes!

If some items have arrows and some don't, this causes a lot of misalignment. We could either align those or we could just drop the arrows completely and make all links blue - that way, it's obvious that they're links regardless if they open in-app or not.
![img_1286](https://cloud.githubusercontent.com/assets/4924246/7484157/89d9a02e-f33a-11e4-842c-de832772f4a7.JPG)

**Comment by astralbodies** [comment]
Whoa that's weird @jancavan - I'm seeing this:

![img_5322](https://cloud.githubusercontent.com/assets/373903/7493092/6f5e44aa-f3c3-11e4-9c23-387851421c46.PNG)

What version of iOS are you running?  Is this an iPhone 6?

**Comment by astralbodies** [comment]
Okay it looks like iOS 8.1 is doing something weird with those margins. I'll check it out @jancavan!

**Comment by astralbodies** [comment]
Looks like there is a crash on iOS 7 with `+ (UIImage *)imageNamed:(NSString *)name inBundle:(NSBundle *)bundle compatibleWithTraitCollection:(UITraitCollection *)traitCollection NS_AVAILABLE_IOS(8_0);` loading the World icon.

**Comment by jancavan** [comment]
@astralbodies sorry I forgot to mention that. Yup, I have an iPhone 6, iOS version is 8.2.

**Comment by jancavan** [comment]
@astralbodies just checked, looks good now :+1:

**Comment by astralbodies** [comment]
Whoo thanks for the review @jancavan :smile:
