### ISSUE TITLE
Do not inherit WPTableViewCell

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#260]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/2491#issuecomment-100250151

Change all of the cells in stats to `UITableViewCell` for the superclass in our implementations. `WPTableViewCell` provides the additional horizontal padding on iPad which we no longer desire.

cc: @aerych

**Comment by aerych** [comment]
\o/ :)
