### ISSUE TITLE
Make each section of Today in Insights switch graph selected row

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#261]
When tapping one of the following sections:

![2015-06-03_09-35-11](https://cloud.githubusercontent.com/assets/373903/7962597/d6bf7a80-09d3-11e5-92cc-463baa82930a.png)

Switch to the similarly labeled section on the graph after the view is flipped to "Days".

![2015-06-03_09-35-43](https://cloud.githubusercontent.com/assets/373903/7962615/eb9d17aa-09d3-11e5-95d7-18620bd21eb1.png)

**Comment by isaackeyet** [comment]
...And use the same horizontal layout if the screen is small enough. :)
