### ISSUE TITLE
Tapping "More" then cancel does not restore previous tab. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPressCom-Stats-iOS#272]
To reproduce:

- On an iPhone pull up the stats screen. 
- Be in portrait orientation
- Have the Insights tab selected.
- Tap the More button. 
- Cancel the action sheet that appears. 
- You are now on the Days tab instead of the Insights tab. 

It looks like just tapping the more button is causing the switch to the Days stats

**Comment by astralbodies** [comment]
D'oh! Thanks for reporting the issue @aerych!
