### ISSUE TITLE
Icons need to be updated from Noticons to Gridicons

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPressCom-Stats-iOS#327]
Icons have been updated on the Web version so we need these updated on the Android app.

Update:

As an example,

**iOS icons (using Noticons):**
![screenshot 2015-10-08 15 01 02](https://cloud.githubusercontent.com/assets/4924246/10381187/8716bf80-6dcd-11e5-8838-dce7bde047e9.png)

**Web icons (using Gridicons):**
![screenshot 2015-10-08 15 02 20](https://cloud.githubusercontent.com/assets/4924246/10381200/a0408874-6dcd-11e5-8743-898391936639.png)

/cc @astralbodies

**Comment by astralbodies** [comment]
@jancavan I'll get you a list of icons and sizes I'll need. There are a few places in stats I use the actual font as well and I may choose to just replace those cases with PNGs.

**Comment by jancavan** [comment]
@astralbodies Sure, sounds good. If we're replacing them all with PNGs instead, we'll probably need all of the icons updated then. Let me know what sizes they should be in as well, thanks.

**Comment by astralbodies** [comment]
Here's a list of what I already have as an image and will need replacement images for:

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-comment_normal%403x.png)
```
icon-comment_normal.png
icon-comment_normal@2x.png
icon-comment_normal@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-comment_pressed%403x.png)
```
icon-comment_pressed.png
icon-comment_pressed@2x.png
icon-comment_pressed@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-eye_normal%403x.png)
```
icon-eye_normal.png
icon-eye_normal@2x.png
icon-eye_normal@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-eye_pressed%403x.png)
```
icon-eye_pressed.png
icon-eye_pressed@2x.png
icon-eye_pressed@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-star_normal%403x.png)
```
icon-star_normal.png
icon-star_normal@2x.png
icon-star_normal@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-star_pressed%403x.png)
```
icon-star_pressed.png
icon-star_pressed@2x.png
icon-star_pressed@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-text_normal%403x.png)
```
icon-text_normal.png
icon-text_normal@2x.png
icon-text_normal@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-text_pressed%403x.png)
```
icon-text_pressed.png
icon-text_pressed@2x.png
icon-text_pressed@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-trophy_normal%403x.png)
```
icon-trophy_normal.png
icon-trophy_normal@2x.png
icon-trophy_normal@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-user_normal%403x.png)
```
icon-user_normal.png
icon-user_normal@2x.png
icon-user_normal@3x.png
```

16x16 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-user_pressed%403x.png)
```
icon-user_pressed.png
icon-user_pressed@2x.png
icon-user_pressed@3x.png
```

20x20 ![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/world%403x.png)
```
world.png
world@2x.png
world@3x.png
```
I think this one is being deprecated though?

**Comment by astralbodies** [comment]
I'll get a list of the remaining images shortly @jancavan (see the last comment here)

**Comment by jancavan** [comment]
@astralbodies Okay, thanks. Yup, we're no longer using the globe icon.

I opened a new issue for that about a week ago https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/333

**Comment by astralbodies** [comment]
@jancavan: Here's a better list of icons I need generated. Can you create vector PDFs for each of the image sizes and in black & white?

![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-comment_normal%403x.png) 16x16, 25x25
![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-eye_normal%403x.png) 16x16, 25x25
![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-star_normal%403x.png) 16x16, 25x25
![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-text_normal%403x.png) 16x16
![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-trophy_normal%403x.png) 16x16
![](https://raw.githubusercontent.com/wordpress-mobile/WordPressCom-Stats-iOS/develop/WordPressCom-Stats-iOS/icon-user_normal%403x.png) 16x16, 25x25
![2015-11-03_07-08-53](https://cloud.githubusercontent.com/assets/373903/10908772/c3d94bd2-81f9-11e5-823e-990b1f0ea323.png) 20x20
![2015-11-03_07-09-30](https://cloud.githubusercontent.com/assets/373903/10908786/d63e99a8-81f9-11e5-9295-a8848531de99.png) 20x20
![2015-11-03_07-09-49](https://cloud.githubusercontent.com/assets/373903/10908792/e29f76b8-81f9-11e5-91f5-8552ad7c3842.png) 20x20
![2015-11-03_07-11-14](https://cloud.githubusercontent.com/assets/373903/10908817/19a9b088-81fa-11e5-9adb-1c66346280f2.png) 8x13 (this is the side of the iOS chevron - no padding)
![2015-11-03_07-12-52](https://cloud.githubusercontent.com/assets/373903/10908848/4e79cc08-81fa-11e5-8aaa-7c56a34d0d52.png) 20x20 (if it changed)

**Comment by jancavan** [comment]
@astralbodies here's a few icons in PDF that you can use to test. They're just black/transparent. Let me know if they work :smile: 
https://cloudup.com/cVxQ-zzZUEx

**Comment by jancavan** [comment]
@astralbodies icons in b&w. Let me know if there's anything I missed https://cloudup.com/c9oTFI9M5cI

The gravatar placeholder icon has not changed.

**Comment by astralbodies** [comment]
@jancavan Looks like the @3x images are the wrong size - they should be 48x48 & 75x75 not 64x64 & 100x100. Can you recreate those? Thanks!! :smile:

**Comment by jancavan** [comment]
@astralbodies here are the corrected sizes: https://cloudup.com/ctk1YLGTD-v

Let me know of these work! Thanks :smile:

**Comment by jancavan** [comment]
@astralbodies added text icon @3x sizes https://cloudup.com/cXsIuPuQ0D6

**Comment by jancavan** [comment]
@astralbodies Share icons https://cloudup.com/cEQov8vhKZQ

**Comment by jancavan** [comment]
@astralbodies External link icons https://cloudup.com/cRc1juLXovq
