### ISSUE TITLE
Remove web placeholder icon

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPressCom-Stats-iOS#333]
As mentioned here:
https://github.com/wordpress-mobile/WordPress-Android/issues/3320#issuecomment-150706097

1. Favicon placeholder icon needs to be removed
2. Link icon needs to be replaced with external link icon

**iOS:**
![img_2547](https://cloud.githubusercontent.com/assets/4924246/10706223/f2f89c78-7999-11e5-8b66-7ef481e04a4a.png)

**On Calypso, we're only using an external link icon without the placeholder favicon:**
![screenshot-2015-10-23-15 24 02](https://cloud.githubusercontent.com/assets/4924246/10706272/613c189a-799a-11e5-920a-33dd17514bd5.png)

**Comment by astralbodies** [comment]
@jancavan I pinged you privately but also wanted to do it here for good measure - I need a 20x20 version of the share image (B&W). Thanks!

**Comment by astralbodies** [comment]
Closed with #349
