### ISSUE TITLE
Test if noticons load correctly when used as a framework

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPressCom-Stats-iOS#348]
In `WPFontManager+Stats.m`, the noticons font is dynamically loaded like this

```obj-c
NSString *resourceName = [NSString stringWithFormat:@"%@/%@", kBundle, name];
NSURL *url = [[NSBundle bundleForClass:self] URLForResource:resourceName withExtension:@"otf"];
NSData *fontData = [NSData dataWithContentsOfURL:url];
```

The problem with this is that `self` is actually `WPFontManager` as this is just a class category. So the bundle to use is `WordPressShared`.

This only works on WordPress-iOS because `Noticons-Regular.otf` is also there, so the `-[UIFont fontWithName:size:]` call in `noticonsReguarFontOfSize:` succeeds, and `dynamicallyLoadStatsFontResourceNamed:` is never called

**Comment by astralbodies** [comment]
Luckily I'm getting rid of noticons in a few minutes :smile:

**Comment by astralbodies** [comment]
Reopening - will let the PR close this issue.
