### ISSUE TITLE
Posts & Pages stats do not expand 

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPressCom-Stats-iOS#368]
Clicking on an individual page/post doesn’t go to the expanded stats for that particular page/post. It just goes nowhere.

![img_3926](https://cloud.githubusercontent.com/assets/1158819/12097164/f1c8b4b4-b2ce-11e5-9847-cac6d06d588e.jpg)

In the screenshot, for instance, clicking “On the Importance…” and “Happy Birthday, Dad” does nothing.

Furthermore, if I click “View All” to see the full list, clicking on any of the individual pages/posts now takes me to the page/post itself, rather than the expanded stats.

Reported by @dennishhong

**Comment by astralbodies** [comment]
@kwonye is this on WPiOS 5.8 or 5.9 internal?

**Comment by astralbodies** [comment]
Actually this is broken for both builds - it's fixed with #362 but I haven't added the fixes yet to the WPiOS build.
