### ISSUE TITLE
Special Characters displaying incorrectly on "Latest Post Summary" module

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPressCom-Stats-iOS#377]
It's showing the HTML characters instead of their actual value:

![img_2880](https://cloud.githubusercontent.com/assets/4924246/12461609/a8955f3e-bf6e-11e5-9495-795b5b5fd7a2.jpg)

/cc @astralbodies

**Comment by astralbodies** [comment]
Yeah this is technically an API issue. If nobody is willing to fix it I'll have to write in a work-around.
