### ISSUE TITLE
Insights "All-time" module header can run off screen on small devices

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPressCom-Stats-iOS#386]
The string "All-time posts, views, and visitors" can be longer when translated, and instead of being cut off gracefully (e.g. with an ellipsis) on smaller devices, it runs off the screen:

![2016-02-01 16 20 26](https://cloud.githubusercontent.com/assets/8658164/12723391/3456bec8-c901-11e5-8403-38293780a742.png)

Tested in Spanish on iPhone 6, iOS 9.2.1, app beta v. 5.9.0.20160126.

**Comment by astralbodies** [comment]
@rachelmcr This was fixed but didn't make it into the 5.9 build. Can you verify its still an issue with the 6.0 internal beta comes out?

**Comment by rachelmcr** [comment]
Ah! Just checked the 6.0 build and this is fixed. I'll close it. Thanks!
