### ISSUE TITLE
Crash on load – unable to dequeue graph background view

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPressCom-Stats-iOS#424]
I've seen a crash when trying to load / display the stats view controller, due to the collection view being unable to dequeue a particular view:

```
2016-07-27 20:41:29.580 WordPress[90406:9219032] *** Assertion failure in -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UICollectionView.m:3994
```

```
2016-07-27 20:43:15.592 WordPress[90406:9219032] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: WPStatsCollectionElementKindGraphBackground with identifier GraphBackgroundView - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
```

I can reproduce this consistently in my in-progress My Sites split view controller branch on WPiOS: `feature/ipad-splitview-mysites`.

To reproduce:

* Run the app in the iPad Air 2 simulator
* In landscape, open the narrowest multitasking split on the right hand side.
* Select a Blog, and view stats in the right pane:

![simulator screen shot 27 jul 2016 22 13 29](https://cloud.githubusercontent.com/assets/4780/17192709/9401560e-5447-11e6-8acf-c17d3187eecf.png)

* Rotate to portrait:

![simulator screen shot 27 jul 2016 22 13 27](https://cloud.githubusercontent.com/assets/4780/17192712/964bea0a-5447-11e6-9bd6-aaffcfe9c381.png)

* Tap the Back button to go back to the blog detail view controller:

![simulator screen shot 27 jul 2016 22 13 21](https://cloud.githubusercontent.com/assets/4780/17192723/9f77a7ae-5447-11e6-9cca-2c63e94fcdd7.png)

* Rotate back to landscape
* Crash!

The issue seems to be fixable by simply reordering the method calls in `viewDidLoad` of `WPStatsGraphViewController`:

```
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    [self.collectionView registerClass:[WPStatsGraphBarCell class] forCellWithReuseIdentifier:CategoryBarCell];
    [self.collectionView registerClass:[UICollectionReusableView class] forSupplementaryViewOfKind:UICollectionElementKindSectionFooter withReuseIdentifier:FooterView];
    [self.collectionView registerClass:[WPStatsGraphBackgroundView class] forSupplementaryViewOfKind:WPStatsCollectionElementKindGraphBackground withReuseIdentifier:GraphBackgroundView];

    self.collectionView.backgroundColor = [UIColor lightGrayColor];
    
    self.flowLayout.scrollDirection = UICollectionViewScrollDirectionVertical;
    self.collectionView.allowsMultipleSelection = YES;
    self.collectionView.showsHorizontalScrollIndicator = NO;
    self.collectionView.showsVerticalScrollIndicator = NO;
    self.collectionView.scrollEnabled = NO;
    self.collectionView.contentInset = UIEdgeInsetsMake(0.0f, 15.0f, 10.0f, 40.0f);
}
```

Here the cell class registrations are moved above the other view setup code. The stack trace indicated that setting the `contentInset` caused cells to be loaded, but this was before their classes were registered.

**Comment by astralbodies** [comment]
Thanks so much for solving this one! Without using the split view controller branch I cannot trigger the problem in StatsDemo or the main WPiOS app. I really am flummoxed with the order of operations causing this crash. Most of the crashes are on iPhones!
