### ISSUE TITLE
Switch country flags to use emoji character rather than Gravatar

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#435]
A new field, `flag_emoji`, will be available (or may already be) for representing the country's flag icon. Switch over to that instead of using the `flag_icon` URL. There was a Gravatar caching issue affecting the flag icons and while it is fixed it makes sense to use what's available without hitting the Internet again.

Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/5206

**Comment by elibud** [comment]
Addressed in: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/440
