### ISSUE TITLE
Insights: Time since a post was published does not update consistently

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPressCom-Stats-iOS#437]
In the "Latest Post Summary" module on the Insights tab, the time since the post was published does not update consistently, and pull to refresh does not refresh it.

After publishing a post, I checked my stats and saw the module update from "It's been <1 hour" to "It's been 1 hour" and then to "It's been 4 hours" since the post was published. However, it seems to be stuck at that. It has been a day since I published the post, which the stats in the browser reflects accurately:

![screen shot 2017-03-08 at 4 17 37 pm](https://cloud.githubusercontent.com/assets/8658164/23712684/90d4e3d6-041b-11e7-9231-8e8f4f2fbe11.png)

I also see the correct time on the post in the Blog Posts list in the app:

![2017-03-08 16 17 06](https://cloud.githubusercontent.com/assets/8658164/23712721/abf164fa-041b-11e7-82e2-887cf2fc0fa2.png)

But even though other stats on the Insights tab are updating (e.g. the View count increased after the post received a new view) the "time since" is stuck at "It's been 4 hours":

![2017-03-08 16 16 56](https://cloud.githubusercontent.com/assets/8658164/23712781/d0b057ec-041b-11e7-84fb-e72ab8f5ba04.png)

Pull to refresh the stats will refresh other stats on that tab, but not the "time since" information.

Originally reported by @catehstn. I tested and reproduced the issue on iPhone 6, iOS 10.2.1, WPiOS 7.1.0.20170306.

**Comment by astralbodies** [comment]
Closing issue and migrating to new repo.
